/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef agent_CONSTANTS_H
#define agent_CONSTANTS_H

#include "agent_types.h"

namespace jaegertracing { namespace agent { namespace thrift {

class agentConstants {
 public:
  agentConstants();

};

extern const agentConstants g_agent_constants;

}}} // namespace

#endif
