/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aggregation_validator_CONSTANTS_H
#define aggregation_validator_CONSTANTS_H

#include "aggregation_validator_types.h"

namespace jaegertracing { namespace thrift {

class aggregation_validatorConstants {
 public:
  aggregation_validatorConstants();

};

extern const aggregation_validatorConstants g_aggregation_validator_constants;

}} // namespace

#endif
