/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "aggregation_validator_constants.h"

namespace jaegertracing { namespace thrift {

const aggregation_validatorConstants g_aggregation_validator_constants;

aggregation_validatorConstants::aggregation_validatorConstants() {
}

}} // namespace

