/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "baggage_constants.h"

namespace jaegertracing { namespace thrift {

const baggageConstants g_baggage_constants;

baggageConstants::baggageConstants() {
}

}} // namespace

