/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef baggage_CONSTANTS_H
#define baggage_CONSTANTS_H

#include "baggage_types.h"

namespace jaegertracing { namespace thrift {

class baggageConstants {
 public:
  baggageConstants();

};

extern const baggageConstants g_baggage_constants;

}} // namespace

#endif
