/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dependency_constants.h"

namespace jaegertracing { namespace thrift {

const dependencyConstants g_dependency_constants;

dependencyConstants::dependencyConstants() {
}

}} // namespace

