/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dependency_CONSTANTS_H
#define dependency_CONSTANTS_H

#include "dependency_types.h"

namespace jaegertracing { namespace thrift {

class dependencyConstants {
 public:
  dependencyConstants();

};

extern const dependencyConstants g_dependency_constants;

}} // namespace

#endif
