/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef jaeger_CONSTANTS_H
#define jaeger_CONSTANTS_H

#include "jaeger_types.h"

namespace jaegertracing { namespace thrift {

class jaegerConstants {
 public:
  jaegerConstants();

};

extern const jaegerConstants g_jaeger_constants;

}} // namespace

#endif
