/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sampling_constants.h"

namespace jaegertracing { namespace sampling_manager { namespace thrift {

const samplingConstants g_sampling_constants;

samplingConstants::samplingConstants() {
}

}}} // namespace

