/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tracetest_CONSTANTS_H
#define tracetest_CONSTANTS_H

#include "tracetest_types.h"

namespace jaegertracing { namespace crossdock { namespace thrift {

class tracetestConstants {
 public:
  tracetestConstants();

};

extern const tracetestConstants g_tracetest_constants;

}}} // namespace

#endif
