/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tracetest_constants.h"

namespace jaegertracing { namespace crossdock { namespace thrift {

const tracetestConstants g_tracetest_constants;

tracetestConstants::tracetestConstants() {
}

}}} // namespace

