list(APPEND BASE_COMPILE_FLAGS_CLANG_GNU -Wall -Wextra -pedantic -Werror)
list(APPEND BASE_COMPILE_FLAGS_MSVC /W4 /WX)
list(
  APPEND
  BASE_COMPILE_FLAGS
  "$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>,$<CXX_COMPILER_ID:GNU>>:${BASE_COMPILE_FLAGS_CLANG_GNU}>"
  "$<$<CXX_COMPILER_ID:MSVC>:${BASE_COMPILE_FLAGS_MSVC}>")
